# Generated by Django 3.2.9 on 2023-06-23 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='media/patient')),
                ('dob', models.DateField(null=True)),
                ('blood_group', models.CharField(max_length=3, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='media/doctor')),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('dob', models.DateField(null=True)),
                ('bio', models.TextField(blank=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('pricing', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('experience', models.CharField(max_length=5, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
