# Generated by Django 4.2.2 on 2023-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
