# Generated by Django 3.2.9 on 2023-07-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230718_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timing'),
        ),
    ]
