# Generated by Django 3.2.9 on 2023-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230625_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='img/patient/default.png', null=True, upload_to=''),
        ),
    ]
