# Generated by Django 4.2.2 on 2023-06-29 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_patient_alter_review_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
    ]
