# Generated by Django 4.2.2 on 2023-07-21 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_payment_method_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_on',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='eSewa', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
