# Generated by Django 4.2.2 on 2023-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_invoice_paid_on_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='eSewa', max_length=15, null=True),
        ),
    ]
