# Generated by Django 4.2.2 on 2023-07-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
    ]
