# Generated by Django 3.2.9 on 2023-06-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_patient_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='patient'),
        ),
    ]
