# Generated by Django 3.2.9 on 2023-06-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230627_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_id',
            new_name='clinic',
        ),
    ]
