# Generated by Django 3.2.9 on 2023-06-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_clinic_id_doctor_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
